version: "3.8"

services:

  backend:
    image: guru0114/stayhive-backend:latest
    container_name: stayhive-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: guru0114/stayhive-frontend:latest
    container_name: stayhive-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
