apiVersion: v1
kind: Service
metadata:
  name: stayhive-backend-service
spec:
  selector:
    app: stayhive-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP